name: Nightly Build
on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * *'

jobs:
  unity_builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: /Library
          key: Library-${{ hashFiles('Assets/*') }}
          restore-keys:
            Library-
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-11
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows
          unityVersion: 2021.1.17f1
      - name: Zip release
        uses: vimtor/action-zip@v1
        with:
          files: /build/StandaloneWindows/
          dest: winbuild.zip
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Post release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}"
          prerelease: true
          title: "Nightly Build ${{ steps.date.outputs.date }}"
          files: |
            winbuild.zip
